# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ishaan Paranjape
tagline:             'PhD student, UC Santa Cruz'
description:         'Personal website of Ishaan Paranjape'
url:                 https://ishaan95.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# From https://mmistakes.github.io/minimal-mistakes/docs/posts/ Copyright 2021 Michael Rose
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
