title: Ishaan's Notes
description: My notes as I learn new things.
author: "Ishaan Paranjape"

theme: minima

base_url: /gh-pages-minima-starter

# Minima social links
twitter_username: ishaanpepper
github_username: ishaan95
linkedin_username: ishaan-paranjape-10829b13a
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
