# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ishaan Paranjape
tagline:             'UC Santa Cruz'
description:         'Personal website of Ishaan Paranjape'
url:                 https://ishaan95.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
